import { createHelpController, helpResolver } from './tooltip-engine.mjs';
export const helpConfig = {
  id: 'gurps-action-chases',
  scope:
    '.gac-app, [data-tool="actionChases"], [name^="gurps-action-chases."], [data-key^="gurps-action-chases."], [data-tool="gurps-action-chases"], [data-control="gurps-action-chases"]',
  actions: {
    new: 'Create a new chase setup.',
    import: 'Import a chase JSON file into a new setup for review.',
    export: 'Download the current chase for backup or reuse.',
    exportRecovery: 'Download recovery data for this chase.',
    demo: 'Create a demonstration chase with example participants.',
    addCharacter: 'Add an on-foot participant; an actor link is optional.',
    addVehicle: 'Add a vehicle, then assign its driver and passengers.',
    addCrew: 'Add or assign a driver or passenger to this vehicle.',
    crew: 'Manage who is aboard, who drives, and planned transfers.',
    actor: 'Import participant information from an actor for review.',
    edit: 'Edit this chase participant’s saved details.',
    duplicate: 'Create a separate copy of this chase participant.',
    remove: 'Remove this participant from the chase; the linked actor is retained.',
    start: 'Start the chase with the current participants and initial range.',
    restart: 'Restart the chase workflow. Review the confirmation before proceeding.',
    pause: 'Pause the chase workflow.',
    resume: 'Resume this paused chase.',
    configure: 'Configure the chase, its range, and combat timing.',
    leader: 'Choose the participant whose roll leads this side.',
    declare: 'Choose this side’s manoeuvre and any required options.',
    quickDeclare: 'Use the displayed manoeuvre for this declaration.',
    reveal: 'Reveal the submitted declarations when both sides are ready.',
    roll: 'Make this participant’s chase roll using the displayed modifiers.',
    manualRoll: 'Enter the original dice total of a roll made elsewhere.',
    skillRoll: 'Make an additional labelled skill roll for this participant.',
    check: 'Resolve the required follow-up check and record its result.',
    modifiers: 'Edit the modifiers used for this chase roll.',
    condition: 'Record this participant’s condition or recovery state in the chase.',
    task: 'Resolve this action by rolling, entering original dice, or recording an external result as available.',
    passTask: 'Pass this optional action without resolving a roll.',
    passSide: 'Pass the optional actions for this side.',
    range: 'Choose the permitted range outcome from the resolved contest.',
    override: 'Record a GM adjustment to the chase state.',
    undo: 'Restore an earlier chase state. This does not reverse external GGA damage or other actor changes.',
    note: 'Add a note to the chase record.',
    gga: 'Open the linked actor’s GGA controls for an external action.',
    show: 'Show this chase view.',
    help: 'Open the module’s chase guidance and user-guide link.',
  },
  fields: {
    name: 'Name used for this chase or participant.',
    side: 'Assign this participant to the quarry or pursuing side.',
    role: 'Choose whether this crew member is driving or acting as a passenger.',
    speed: 'Top Move used for chase calculations; review imported values for this mode of travel.',
    handling: 'Vehicle Handling modifier used with its operator’s chase skill.',
    sr: 'Vehicle Stability Rating, used for failed stunts and control checks.',
    sm: 'Size Modifier of the vehicle being targeted.',
    bulk: 'Weapon Bulk as a signed value, normally zero or negative.',
    acc: 'Weapon Accuracy used when the chase manoeuvre permits it.',
    band: 'Current range band between the sides.',
    static: 'Use the static-contest option when applicable to this chase.',
    forcedStatic: 'Force the configured static contest for this resolution.',
    comp: 'Modifier from a complementary skill result; this field does not roll that skill.',
    penalty: 'Risk penalty for the declared stunt.',
    modifier: 'Signed adjustment to this roll.',
    extra: 'Other attack modifiers not already included in the displayed chase calculation.',
    mode: 'Choose a module roll, original dice from an external roll, or the available GM resolution.',
    total: 'Original 3d6 dice total, not margin of success or failure.',
    target:
      'Skill value for this check. Follow the field label and preview for modifiers already included.',
    baseOverride: 'Override the base skill used for this chase roll.',
    stuntSkill: 'Choose the skill used for this stunt.',
    status: 'Record the participant’s chase condition.',
    hp: 'HP recorded in the chase. Resolve linked actor damage separately in GGA.',
    recovered: 'Confirm the recovery result recorded for this participant.',
    recovery: 'Recovery value used by the chase’s pending recovery check.',
    reviewed:
      'Confirm you have resolved the listed damage or other consequences before continuing.',
    when: 'Choose when this crew change takes effect in the chase.',
    vehicleId: 'Destination vehicle for this crew assignment or transfer.',
    personId: 'Choose the existing character or create a new crew member.',
    originVehicleId: 'Vehicle this new character starts aboard; select On foot if appropriate.',
    footSkill: 'DX-based chase skill level to use after disembarking.',
    footSkillName: 'Name of the skill used while this participant is on foot.',
    blind: 'Keep the result hidden from players using a blind roll.',
    whisper: 'Limit this result to the configured private audience.',
    otf: 'Native GGA expression to roll. Include chase modifiers; the pending task still needs its result recorded.',
    sourceSkill: 'Choose which actor skill to copy into the chase participant.',
    notes: 'Notes saved with this chase participant.',
    note: 'Record the action’s outcome or the reason for a GM decision.',
    file: 'Choose a chase JSON export. Actor links and player assignments require review after import.',
  },
  rules: [
    ['[data-chase-picker]', 'Switch to another saved chase.'],
    [
      '[data-native-roll]',
      'Roll the expression through GGA; then enter its original dice or record the outcome to finish this task.',
    ],
    ['[data-cancel]', 'Close this form without submitting its edits.'],
  ],
  actionAttributes: ['data-do', 'data-action'],
};
let resolve = helpResolver(helpConfig);

export const helpController = createHelpController({ ...helpConfig, resolve });
if (globalThis.Hooks) {
  Hooks.once('init', () => helpController.register());
  Hooks.once('ready', () => helpController.start());
}
